# Generated by Django 3.2.9 on 2022-11-02 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupla', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 9, 45, 39, 723742)),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(choices=[(0, 'JavaScript'), (1, 'Java'), (2, 'Python'), (4, 'Android'), (5, 'Apple'), (6, 'Other')], max_length=255),
        ),
    ]
