# Generated by Django 3.2.9 on 2022-11-02 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupla', '0002_auto_20221102_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 9, 55, 19, 427961)),
        ),
    ]
