# Generated by Django 3.2.9 on 2022-11-02 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupla', '0003_alter_project_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 9, 59, 43, 249452)),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.IntegerField(choices=[(0, 'JavaScript'), (1, 'Java'), (2, 'Python'), (4, 'Android'), (5, 'Apple'), (6, 'Other')], default=6),
        ),
    ]
